#
# This source code is the confidential, proprietary information of
# Dress Club  here in, you may not disclose such Information,
# and may only use it in accordance with the terms of the license
# agreement you entered into with Dress Club.
#
# 2018: Dress Club.
# All Rights Reserved.
#
---
- name: Create Kubernetes Services
  hosts: localhost
  connection: local
  gather_facts: False
     
  tasks:
  
  - name: Azure Login
    command: "az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_SECRET --tenant $AZURE_TENANT"
    
  - name: Azure Kubernetes get Credentials
    command: "az aks get-credentials --resource-group {{ azure_resource_group_name }} --name {{ azure_aks_name }}"

  - name: Create Kubernetes file
    template: src=templates/tdcbackend.yaml dest=/tmp/backend.play.yaml
    delegate_to: localhost
  
  - name: Deploy service in Kubernete
    command: "kubectl apply -f /tmp/backend.play.yaml"
